name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /usr/local/lib/android
          df -h

      - name: Install Dependencies
        run: |
          sudo apt-get update || sudo apt-get update || true
          sudo apt-get install -y \
            gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
            libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo python3 dtc \
            bc build-essential zip curl libstdc++6 git wget

      - name: Initialize Repo & Sync
        run: |
          mkdir ~/twrp && cd ~/twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc --all) --force-sync --no-tags --no-clone-bundle

      - name: Clone Device Tree
        run: |
          cd ~/twrp
          # Mengambil branch 'twrp' dari repo kamu
          git clone https://github.com/opek098/android_device_meizu_note21pro -b twrp device/meizu/note21pro

      - name: Start Compilation
        run: |
          cd ~/twrp
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch twrp_note21pro-eng
          mka recoveryimage -j$(nproc --all)

      - name: Upload Recovery
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-Meizu-Note21Pro
          path: ~/twrp/out/target/product/note21pro/*.img
